In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
import os
os.getcwd()

'C:\\Users\\PRATEEK'

In [3]:
os.chdir('/')

In [4]:
os.chdir('C:/Users/PRATEEK/Desktop/Sentiment Analysis Project')

In [5]:
dataset=pd.read_csv('Train_data.csv')

In [6]:
dataset

Review  Liked
0                              Wow... Loved this place.      1
1                                    Crust is not good.      0
2             Not tasty and the texture was just nasty.      0
3     Stopped by during the late May bank holiday of...      1
4     The selection on the menu was great and so wer...      1
5        Now I am getting angry and I want my damn pho.      0
6                 Honeslty it didn't taste THAT fresh.)      0
7     The potatoes were like rubber and you could te...      0
8                             The fries were great too.      1
9                                        A great touch.      1
10                             Service was very prompt.      1
11                                   Would not go back.      0
12    The cashier had no care what so ever on what I...      0
13    I tried the Cape Cod ravoli, chicken, with cra...      1
14    I was disgusted because I was pretty sure that...      0
15    I was shocked because no signs indicate cash o...      0
16                                  Highly recommended.      1
17               Waitress was a little slow in service.      0
18    This place is not worth your time, let alone V...      0
19                                 did not like at all.      0
20                                  The Burrittos Blah!      0
21                                   The food, amazing.      1
22                                Service is also cute.      1
23    I could care less... The interior is just beau...      1
24                                   So they performed.      1
25    That's right....the red velvet cake.....ohhh t...      1
26    This hole in the wall has great Mexican street...      1
27    Took an hour to get our food only 4 tables in ...      0
28                    The worst was the salmon sashimi.      0
29    Also there are combos like a burger, fries, an...      1
...                                                 ...    ...
1057                              The entrance is good.      1
1058         The gatekeeper greetes in friendly manner.      1
1059     They have packaging service for leftover food.      1
1060                     Variety of desserts were less.      0
1061         They have speciality in north indian food.      1
1062              They have open area for kids to play.      1
1063  Customer can provide self assessment survey th...      1
1064             Music is there as per customer choice.      1
1065     They have arrangements for seperate functions.      1
1066                             Parking area is small.      0
1067                      Have wide variety of choices.      1
1068               There combo offer is just fantastic.      1
1069  The atmosphere is not good at there, crowd was...      0
1070              Great variety of snacks and sizzlers.      1
1071  Well organised staff with great sincerity insi...      1
1072       At price are bit high in comparison of food.      0
1073  They have no arrangements for even small parties.      0
1074   The mexican meal is must if you have fond of it.      1
1075  They also have ice cream parlour at the upper ...      1
1076  Do not buy a single italian dish, they are jus...      0
1077  Do not spend single peny on them, else one wil...      0
1078                    The taste is above expectation.      1
1079            A perfect hub for a small get together.      1
1080  The staff is so rude. They don't even listen t...      0
1081                           Such a awful experience.      0
1082  That's my favourite place for refershments and...      1
1083                 Sitting arrangement is impressive.      1
1084   They don't even have enough seats for customers.      0
1085  Owner is harsh in its behaviour. He doesn't kn...      0
1086  A big thumbs up for such a nice hosting by ami...      1

[1087 rows x 2 columns]

In [7]:
import string
import nltk
from nltk.corpus import stopwords
def textpreprocess(feature):
    #Remove Punctuations
    remove_punctuation = [char for char in feature if char not in string.punctuation] 
    #Character to sentences
    without_punctuation = "".join(remove_punctuation)
    #Sentences to words
    words = without_punctuation.split(' ')
    #Character without Stopwords
    without_stopwords = [word for word in words if word.lower() not in stopwords.words('english')]
    return without_stopwords

In [8]:
output = textpreprocess(dataset['Review'])
output

['Wow...',
 'Loved',
 'place.Crust',
 'good.Not',
 'tasty',
 'texture',
 'nasty.Stopped',
 'late',
 'May',
 'bank',
 'holiday',
 'Rick',
 'Steve',
 'recommendation',
 'loved',
 'it.The',
 'selection',
 'menu',
 'great',
 'prices.Now',
 'getting',
 'angry',
 'want',
 'damn',
 'pho.Honeslty',
 'taste',
 'fresh.)The',
 'potatoes',
 'like',
 'rubber',
 'could',
 'tell',
 'made',
 'ahead',
 'time',
 'kept',
 'warmer.The',
 'fries',
 'great',
 'too.A',
 'great',
 'touch.Service',
 'prompt.Would',
 'go',
 'back.The',
 'cashier',
 'care',
 'ever',
 'say',
 'still',
 'ended',
 'wayyy',
 'overpriced.I',
 'tried',
 'Cape',
 'Cod',
 'ravoli,',
 'chicken,',
 'cranberry...mmmm!I',
 'disgusted',
 'pretty',
 'sure',
 'human',
 'hair.I',
 'shocked',
 'signs',
 'indicate',
 'cash',
 'only.Highly',
 'recommended.Waitress',
 'little',
 'slow',
 'service.This',
 'place',
 'worth',
 'time,',
 'let',
 'alone',
 'Vegas.did',
 'like',
 'all.The',
 'Burrittos',
 'Blah!The',
 'food,',
 'amazing.Service',
 'also'

In [9]:
#Now the Preprocessing has already been done!
#Creating Bag of Words!
from sklearn.feature_extraction.text import CountVectorizer
word_vector = CountVectorizer(analyzer=textpreprocess)
final_words = word_vector.fit(dataset['Review'])

In [10]:
final_words.vocabulary_

{'Wow': 462,
 'Loved': 256,
 'place': 1618,
 'Crust': 118,
 'good': 1127,
 'tasty': 2038,
 'texture': 2051,
 'nasty': 1473,
 'Stopped': 395,
 'late': 1314,
 'May': 273,
 'bank': 565,
 'holiday': 1212,
 'Rick': 354,
 'Steve': 394,
 'recommendation': 1732,
 'loved': 1365,
 'selection': 1844,
 'menu': 1422,
 'great': 1137,
 'prices': 1662,
 'getting': 1109,
 'angry': 501,
 'want': 2183,
 'damn': 827,
 'pho': 1606,
 'Honeslty': 210,
 'didnt': 867,
 'taste': 2034,
 'fresh': 1081,
 'potatoes': 1649,
 'like': 1338,
 'rubber': 1794,
 'could': 786,
 'tell': 2043,
 'made': 1378,
 'ahead': 482,
 'time': 2072,
 'kept': 1297,
 'warmer': 2187,
 'fries': 1086,
 'touch': 2093,
 'Service': 374,
 'prompt': 1675,
 'Would': 460,
 'go': 1120,
 'back': 556,
 'cashier': 690,
 'care': 683,
 'ever': 977,
 'say': 1823,
 'still': 1973,
 'ended': 958,
 'wayyy': 2201,
 'overpriced': 1546,
 'tried': 2105,
 'Cape': 92,
 'Cod': 103,
 'ravoli': 1715,
 'chicken': 715,
 'cranberrymmmm': 802,
 'disgusted': 891,
 'pretty'

In [11]:
bag_of_words=word_vector.transform(dataset['Review'])

In [12]:
bag_of_words

<1087x2269 sparse matrix of type '<class 'numpy.int64'>'
	with 6024 stored elements in Compressed Sparse Row format>

In [13]:
#Now just Bag of Words is not sufficient so now apply TF-IDF ( Term Freq / Document Freq )
from sklearn.feature_extraction.text import TfidfTransformer
tf_idf = TfidfTransformer().fit(bag_of_words)

In [14]:
final_tf = tf_idf.transform(bag_of_words)
final_tf#This is the output of TF_IDF

<1087x2269 sparse matrix of type '<class 'numpy.float64'>'
	with 6024 stored elements in Compressed Sparse Row format>

In [15]:
pd.DataFrame(final_tf.toarray()[0]) #So this is the Division of TermFreq/DocumFreq

0
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
21    0.0
22    0.0
23    0.0
24    0.0
25    0.0
26    0.0
27    0.0
28    0.0
29    0.0
...   ...
2239  0.0
2240  0.0
2241  0.0
2242  0.0
2243  0.0
2244  0.0
2245  0.0
2246  0.0
2247  0.0
2248  0.0
2249  0.0
2250  0.0
2251  0.0
2252  0.0
2253  0.0
2254  0.0
2255  0.0
2256  0.0
2257  0.0
2258  0.0
2259  0.0
2260  0.0
2261  0.0
2262  0.0
2263  0.0
2264  0.0
2265  0.0
2266  0.0
2267  0.0
2268  0.0

[2269 rows x 1 columns]

In [16]:
#Now we can apply to the ML Model
from sklearn.neighbors import KNeighborsClassifier
baseline_model = KNeighborsClassifier()
baseline_model.fit(final_tf,dataset['Liked'])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [17]:
baseline_model.score(final_tf,dataset['Liked'])

0.8491260349586016

In [18]:
from sklearn.metrics import confusion_matrix,classification_report
clas = confusion_matrix(dataset['Liked'],baseline_model.predict(final_tf))

In [19]:
clas

array([[442,  99],
       [ 65, 481]], dtype=int64)

In [20]:
#deployement
test_set=pd.read_csv('PROJECT TEST DATA.csv')

In [21]:
test_set

Name                Email      Password  \
0       ronnie      ronnie@ussr.com      asdfrwds   
1    katherine      katy@usa.edu.in     784596257   
2        eddie         ed@yahoo.com  4785hjgvc021   
3      Prateek  Feheuxy@outlook.com          4546   
4       Check1  Feheuxy@outlook.com          3156   
5          abc                  abc    1236547812   
6          def                  def   7845vfgb123   
7       Check2  Feheuxy@outlook.com          4567   
8          ghi                  ghi    3698521470   
9       Check3  Feheuxy@outlook.com          7891   
10         jkl                  jkl     1452mjbng   
11         aek                  aek   bgvdfc45874   
12   Checksome  Feheuxy@outlook.com          5643   
13      Vegeta        Abc@gmail.com          5643   
14       Kavya        Abc@gmail.com          5643   
15      Neeraj        Abc@gmail.com          5643   
16        Aman        Abc@gmail.com          5643   
17       Lalit        Abc@gmail.com          5643   
18       Vicky        Abc@gmail.com          5643   
19    Kanishka        Abc@gmail.com          5643   
20      Prince        Abc@gmail.com          5643   
21      Akshit        Abc@gmail.com          5643   
22  Shubhankit        Abc@gmail.com          5643   
23      Akshay        Abc@gmail.com          5643   
24      Adarsh        Abc@gmail.com          5643   
25      Raghav        Abc@gmail.com          5643   
26     Rishabh        Abc@gmail.com          5643   
27     Raushan        Abc@gmail.com          5643   
28      Ananya        Abc@gmail.com          5643   
29     Rishabh        Abc@gmail.com          5643   
..         ...                  ...           ...   
59    Prashant        Abc@gmail.com          5643   
60      Gaurav        Abc@gmail.com          5643   
61       Mohit        Abc@gmail.com          5643   
62    Divydeep        Abc@gmail.com          5643   
63       Samar        Abc@gmail.com          5643   
64    Madhurta        Abc@gmail.com          5643   
65      Muskan        Abc@gmail.com          5643   
66      Shreya        Abc@gmail.com          5643   
67       Arjun        Abc@gmail.com          5643   
68       Sumit        Abc@gmail.com          5643   
69       Sumit        Abc@gmail.com          5643   
70     Prateek        Abc@gmail.com          5643   
71      Deepak        Abc@gmail.com          5643   
72      Chirag        Abc@gmail.com          5643   
73    Abhishek        Abc@gmail.com          5643   
74       Mohit        Abc@gmail.com          5643   
75       Rohit        Abc@gmail.com          5643   
76       Nitin        Abc@gmail.com          5643   
77      Nitesh        Abc@gmail.com          5643   
78      Satvik        Abc@gmail.com          5643   
79     Aashish        Abc@gmail.com          5643   
80      Saumya        Abc@gmail.com          5643   
81     Kuldeep        Abc@gmail.com          5643   
82     Sandeep        Abc@gmail.com          5643   
83       Haris        Abc@gmail.com          5643   
84     Akansha        Abc@gmail.com          5643   
85    Prashant        Abc@gmail.com          5643   
86    Chaitnya        Abc@gmail.com          5643   
87     Nishant        Abc@gmail.com          5643   
88     Mohnish        Abc@gmail.com          5643   

                                           Suggestion  
0                            love the chicken burger.  
1                           i loved your mango drink.  
2                      not good. could have improved.  
3                                Dishes are too gud.   
4                                    Not good taste.   
5                                               good.  
6                                                bad.  
7                                       Great taste.   
8                                          excellent.  
9                                         Delicious.   
10                                             worst.  
11                                         brillian

In [22]:
pre_processed = textpreprocess(test_set['Suggestion'])
BOW = word_vector.transform(pre_processed)
features = tf_idf.transform(BOW)
result1 = baseline_model.predict(features)
result1

array([1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [33]:
def predict(message):
    list1=[]
    for msg in message:
        inputData = msg
        l1=textpreprocess(inputData)
        l2=word_vector.transform(l1)
        l3=tf_idf.transform(l2)
        prediction=baseline_model.predict(l3[0])
        list1.append(prediction)
    return(list1)

In [34]:
df=predict(test_set['Suggestion'])

In [35]:
print(df)


[array([1], dtype=int64), array([1], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64), array([1], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([0], dtype=int64), array([0], dtype=int64), array([0], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([0], dtype=int64), array([0], dtype=int64), array([1], dtype=int64), array([1], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([0], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([0], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([0], dtype=int64), array([0], dtype=int64), array([0], dtype=int64), array([0], dtype=int64), array([0], dtype=int64),

In [38]:
df


[array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], 

In [40]:
print(len(df))

89


In [42]:
df1=pd.DataFrame(df)

In [43]:
df1

0
0   1
1   1
2   1
3   0
4   1
5   1
6   0
7   1
8   1
9   1
10  0
11  0
12  0
13  0
14  1
15  0
16  0
17  0
18  1
19  1
20  1
21  0
22  0
23  1
24  0
25  0
26  1
27  0
28  1
29  1
.. ..
59  1
60  0
61  0
62  1
63  0
64  0
65  0
66  0
67  0
68  0
69  0
70  1
71  1
72  0
73  0
74  0
75  0
76  1
77  0
78  1
79  0
80  1
81  0
82  1
83  0
84  1
85  0
86  1
87  0
88  0

[89 rows x 1 columns]

In [44]:
test_set

Name                Email      Password  \
0       ronnie      ronnie@ussr.com      asdfrwds   
1    katherine      katy@usa.edu.in     784596257   
2        eddie         ed@yahoo.com  4785hjgvc021   
3      Prateek  Feheuxy@outlook.com          4546   
4       Check1  Feheuxy@outlook.com          3156   
5          abc                  abc    1236547812   
6          def                  def   7845vfgb123   
7       Check2  Feheuxy@outlook.com          4567   
8          ghi                  ghi    3698521470   
9       Check3  Feheuxy@outlook.com          7891   
10         jkl                  jkl     1452mjbng   
11         aek                  aek   bgvdfc45874   
12   Checksome  Feheuxy@outlook.com          5643   
13      Vegeta        Abc@gmail.com          5643   
14       Kavya        Abc@gmail.com          5643   
15      Neeraj        Abc@gmail.com          5643   
16        Aman        Abc@gmail.com          5643   
17       Lalit        Abc@gmail.com          5643   
18       Vicky        Abc@gmail.com          5643   
19    Kanishka        Abc@gmail.com          5643   
20      Prince        Abc@gmail.com          5643   
21      Akshit        Abc@gmail.com          5643   
22  Shubhankit        Abc@gmail.com          5643   
23      Akshay        Abc@gmail.com          5643   
24      Adarsh        Abc@gmail.com          5643   
25      Raghav        Abc@gmail.com          5643   
26     Rishabh        Abc@gmail.com          5643   
27     Raushan        Abc@gmail.com          5643   
28      Ananya        Abc@gmail.com          5643   
29     Rishabh        Abc@gmail.com          5643   
..         ...                  ...           ...   
59    Prashant        Abc@gmail.com          5643   
60      Gaurav        Abc@gmail.com          5643   
61       Mohit        Abc@gmail.com          5643   
62    Divydeep        Abc@gmail.com          5643   
63       Samar        Abc@gmail.com          5643   
64    Madhurta        Abc@gmail.com          5643   
65      Muskan        Abc@gmail.com          5643   
66      Shreya        Abc@gmail.com          5643   
67       Arjun        Abc@gmail.com          5643   
68       Sumit        Abc@gmail.com          5643   
69       Sumit        Abc@gmail.com          5643   
70     Prateek        Abc@gmail.com          5643   
71      Deepak        Abc@gmail.com          5643   
72      Chirag        Abc@gmail.com          5643   
73    Abhishek        Abc@gmail.com          5643   
74       Mohit        Abc@gmail.com          5643   
75       Rohit        Abc@gmail.com          5643   
76       Nitin        Abc@gmail.com          5643   
77      Nitesh        Abc@gmail.com          5643   
78      Satvik        Abc@gmail.com          5643   
79     Aashish        Abc@gmail.com          5643   
80      Saumya        Abc@gmail.com          5643   
81     Kuldeep        Abc@gmail.com          5643   
82     Sandeep        Abc@gmail.com          5643   
83       Haris        Abc@gmail.com          5643   
84     Akansha        Abc@gmail.com          5643   
85    Prashant        Abc@gmail.com          5643   
86    Chaitnya        Abc@gmail.com          5643   
87     Nishant        Abc@gmail.com          5643   
88     Mohnish        Abc@gmail.com          5643   

                                           Suggestion  
0                            love the chicken burger.  
1                           i loved your mango drink.  
2                      not good. could have improved.  
3                                Dishes are too gud.   
4                                    Not good taste.   
5                                               good.  
6                                                bad.  
7                                       Great taste.   
8                                          excellent.  
9                                         Delicious.   
10                                             worst.  
11                                         brillian

In [45]:
test_set.insert(4,'Analysis',df1)

In [46]:
test_set

Name                Email      Password  \
0       ronnie      ronnie@ussr.com      asdfrwds   
1    katherine      katy@usa.edu.in     784596257   
2        eddie         ed@yahoo.com  4785hjgvc021   
3      Prateek  Feheuxy@outlook.com          4546   
4       Check1  Feheuxy@outlook.com          3156   
5          abc                  abc    1236547812   
6          def                  def   7845vfgb123   
7       Check2  Feheuxy@outlook.com          4567   
8          ghi                  ghi    3698521470   
9       Check3  Feheuxy@outlook.com          7891   
10         jkl                  jkl     1452mjbng   
11         aek                  aek   bgvdfc45874   
12   Checksome  Feheuxy@outlook.com          5643   
13      Vegeta        Abc@gmail.com          5643   
14       Kavya        Abc@gmail.com          5643   
15      Neeraj        Abc@gmail.com          5643   
16        Aman        Abc@gmail.com          5643   
17       Lalit        Abc@gmail.com          5643   
18       Vicky        Abc@gmail.com          5643   
19    Kanishka        Abc@gmail.com          5643   
20      Prince        Abc@gmail.com          5643   
21      Akshit        Abc@gmail.com          5643   
22  Shubhankit        Abc@gmail.com          5643   
23      Akshay        Abc@gmail.com          5643   
24      Adarsh        Abc@gmail.com          5643   
25      Raghav        Abc@gmail.com          5643   
26     Rishabh        Abc@gmail.com          5643   
27     Raushan        Abc@gmail.com          5643   
28      Ananya        Abc@gmail.com          5643   
29     Rishabh        Abc@gmail.com          5643   
..         ...                  ...           ...   
59    Prashant        Abc@gmail.com          5643   
60      Gaurav        Abc@gmail.com          5643   
61       Mohit        Abc@gmail.com          5643   
62    Divydeep        Abc@gmail.com          5643   
63       Samar        Abc@gmail.com          5643   
64    Madhurta        Abc@gmail.com          5643   
65      Muskan        Abc@gmail.com          5643   
66      Shreya        Abc@gmail.com          5643   
67       Arjun        Abc@gmail.com          5643   
68       Sumit        Abc@gmail.com          5643   
69       Sumit        Abc@gmail.com          5643   
70     Prateek        Abc@gmail.com          5643   
71      Deepak        Abc@gmail.com          5643   
72      Chirag        Abc@gmail.com          5643   
73    Abhishek        Abc@gmail.com          5643   
74       Mohit        Abc@gmail.com          5643   
75       Rohit        Abc@gmail.com          5643   
76       Nitin        Abc@gmail.com          5643   
77      Nitesh        Abc@gmail.com          5643   
78      Satvik        Abc@gmail.com          5643   
79     Aashish        Abc@gmail.com          5643   
80      Saumya        Abc@gmail.com          5643   
81     Kuldeep        Abc@gmail.com          5643   
82     Sandeep        Abc@gmail.com          5643   
83       Haris        Abc@gmail.com          5643   
84     Akansha        Abc@gmail.com          5643   
85    Prashant        Abc@gmail.com          5643   
86    Chaitnya        Abc@gmail.com          5643   
87     Nishant        Abc@gmail.com          5643   
88     Mohnish        Abc@gmail.com          5643   

                                           Suggestion  Analysis  
0                            love the chicken burger.         1  
1                           i loved your mango drink.         1  
2                      not good. could have improved.         1  
3                                Dishes are too gud.          0  
4                                    Not good taste.          1  
5                                               good.         1  
6                                                bad.         0  
7                                       Great taste.          1  
8                                          excellent.         1  
9                                         Delicious.          1

In [47]:
test_set.to_csv('Review Analysis.csv')